name: LinkedIn to Discord Notifier

on:
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos
  workflow_dispatch: # Permite rodar manualmente o workflow

jobs:
  send_notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node index.js
